choco:
- cuda --version=11.4.2.47141
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
# Pin `patchelf` to pre-0.18.0 to avoid corrupting binaries.
# xref: https://github.com/conda-forge/conda-smithy/issues/1737
remote_ci_setup:
  - "conda-forge-ci-setup=3"
  - "patchelf<0.18.0"
